destination: "public/labs-template"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]

ga_tracking_code: "REPLACEME"

subsite: dev
title: labs-template
root: "/labs-template"
icon: fa fa-file-text
github_repo: https://github.com/socrata/labs-template
