destination: "public/soda-swift"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public, Makefile]

ga_tracking_code: "REPLACEME"

subsite: soda-swift
title: SODA Swift SDK (Beta)
root: "/soda-swift"
icon: fa fa-mobile-phone
github_repo: https://github.com/socrata/soda-swift
